apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deploy
  labels:
    app: wp
spec:
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wp
        image: wordpress
        ports:
        - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: db                 
          - name: WORDPRESS_DB_USER
            value: wp
          - name: WORDPRESS_DB_PASSWORD
            value: wp
          - name: WORDPRESS_DB_NAME
            value: wp
          - name: WORDPRESS_TITLE
            value: Example_WebSite
          - name:  WORDPRESS_EMAIL
            value: example@example.com
          - name: WORDPRESS_PASSWORD
            value: example
          - name: WORDPRESS_USER
            value: example
  selector:
    matchLabels:
      app: wp
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: wp
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: wp
